name: manual run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: safiye-alaca
          theme: dark
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/*

