name: Generate Snake Animation

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: safiye-alaca
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
          theme: dark
      - name: Upload animation
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/*
